from . import hr_hospital_person_mixin
from . import hr_hospital_doctor
from . import hr_hospital_patient
from . import hr_hospital_patient_card
from . import hr_hospital_illness_category
from . import hr_hospital_illness
from . import hr_hospital_sample_type
from . import hr_hospital_research_type
from . import hr_hospital_research
from . import hr_hospital_diagnosis
from . import hr_hospital_appointment
from . import hr_hospital_doctor_history
